# Generated by Django 3.0.3 on 2020-11-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='s_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='s_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='s_goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='s_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='s_weight',
            new_name='weight',
        ),
    ]
